export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL ="FETCH_PRODUCTS_FAIL";
export const ADD_CART = "ADD_CART";
export const DECREASE_QUANTIY = "DECREASE_QUANTITY"
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const GET_NUMBER_CART = 'GET_NUMBER_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const DELETE_CART = 'DELETE_CART';
export const WISH_LIST = 'WISH_LIST';
export const SEARCH_LIST = 'SEARCH_LIST';




